<a href="https://colab.research.google.com/github/kushagrasharma-13/Prodigy_ML_01/blob/main/Prodigy_ML_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Regression on Salary Dataset

Correlation

Mean Sqaured Error, Variance Score, R2 Score

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error as MSE, explained_variance_score as EVS, r2_score

In [ ]:
dataset = pd.read_csv("/content/Housing.csv")
dataset

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
dataset.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [ ]:
corr = dataset.corr()
corr.style.background_gradient(cmap = 'coolwarm')

<ipython-input-36-ffd37e1235a7>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr = dataset.corr()

Variations for loading independent variable

In [ ]:
x = dataset.iloc[:,1:4].values
print(x.ndim)

2

In [ ]:
y = dataset["price"].values
print(y.ndim)

1

In [ ]:
x_train, x_test, y_train, y_test = tts(x, y, test_size=0.3, random_state=0)

In [ ]:
LR = LinearRegression()
LR.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = LR.predict(x_test)

In [ ]:
diff = y_test-y_pred

In [ ]:
LR_df = pd.concat([pd.Series(y_pred), pd.Series(y_test),pd.Series(diff)], axis=1)
LR_df.columns = ['Prediction', 'Test', 'Difference']
LR_df

       Prediction     Test    Difference
0    3.959099e+06  4585000  6.259012e+05
1    6.297402e+06  6083000 -2.144020e+05
2    4.242278e+06  4007500 -2.347785e+05
3    7.279070e+06  6930000 -3.490696e+05
4    4.325492e+06  2940000 -1.385492e+06
..            ...      ...           ...
159  3.850668e+06  2940000 -9.106678e+05
160  3.959099e+06  2653000 -1.306099e+06
161  3.688655e+06  3836000  1.473455e+05
162  6.047508e+06  4760000 -1.287508e+06
163  4.791235e+06  7962500  3.171265e+06

[164 rows x 3 columns]

In [ ]:
print("Root Mean Squared Error: ", round(np.sqrt(MSE(y_test, y_pred)), 2))
print("Variance Score: ", round(EVS(y_test, y_pred), 2))
print("R Square Score: ", round(r2_score(y_test, y_pred), 2))

Root Mean Squared Error:  1311537.47
Variance Score:  0.51
R Square Score:  0.5